############################### PugiXML ################################

set(PUGIXML_SOURCE_DIR "${LIBSOURCEY_SOURCE_DIR}/3rdparty/pugixml" CACHE PATH "PugiXML Source Location")
set(PUGIXML_LIBRARY_DIR "${LIBSOURCEY_INSTALL_PREFIX}/share/LibSourcey/3rdparty/lib" CACHE PATH "PugiXML Library Location")

#set(PUGIXML_INSTALL_PATH "${PUGIXML_SOURCE_DIR}" CACHE PATH "PugiXML Install Location")
#set(PUGIXML_LIBRARY_DIR "${LIBSOURCEY_BUILD_DIR}/3rdparty/lib")
set(PUGIXML_INCLUDE_DIRS ${PUGIXML_SOURCE_DIR} "${PUGIXML_SOURCE_DIR}/src")

set(PUGIXML_DEBUG_LIBS "pugixmld")
set(PUGIXML_RELEASE_LIBS "pugixml")

#set(PUGIXML_FOUND 1)
      
include_directories(${PUGIXML_INCLUDE_DIRS})  
link_directories(${PUGIXML_LIBRARY_DIR})
                      
set(LIBSOURCEY_INCLUDE_DIRS ${LIBSOURCEY_INCLUDE_DIRS} ${PUGIXML_INCLUDE_DIRS})
set(LIBSOURCEY_LIBRARY_DIRS ${LIBSOURCEY_LIBRARY_DIRS} ${PUGIXML_LIBRARY_DIR})
set(LIBSOURCEY_DEBUG_LIBS   ${LIBSOURCEY_DEBUG_LIBS}   ${PUGIXML_DEBUG_LIBS})
set(LIBSOURCEY_RELEASE_LIBS ${LIBSOURCEY_RELEASE_LIBS} ${PUGIXML_RELEASE_LIBS})