############################### Libuv ################################

set(LIBUV_SOURCE_PATH "${LIBSOURCEY_SOURCE_DIR}/3rdparty/libuv" CACHE PATH "Libuv Path")
set(LIBUV_LIBRARY_DIR "${LIBUV_SOURCE_PATH}/lib")
set(LIBUV_LIBRARY_DIR ${LIBUV_LIBRARY_DIR} CACHE PATH "Libuv Library Location")

set(LIBUV_DEBUG_LIBS "uv")
set(LIBUV_RELEASE_LIBS "uv")
      
include_directories("${LIBUV_SOURCE_PATH}/include")  
link_directories(${LIBUV_LIBRARY_DIR})
                      
set(LIBSOURCEY_INCLUDE_DIRS ${LIBSOURCEY_INCLUDE_DIRS} ${LIBUV_SOURCE_PATH})
set(LIBSOURCEY_LIBRARY_DIRS ${LIBSOURCEY_LIBRARY_DIRS} ${LIBUV_LIBRARY_DIR})
set(LIBSOURCEY_DEBUG_LIBS   ${LIBSOURCEY_DEBUG_LIBS}   ${LIBUV_DEBUG_LIBS})    
set(LIBSOURCEY_RELEASE_LIBS ${LIBSOURCEY_RELEASE_LIBS} ${LIBUV_RELEASE_LIBS})    